# Generated by Django 6.0.4 on 2026-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('contract_duration', models.CharField(help_text='MMM-yyyy format (e.g., Jan-2024)', max_length=20)),
                ('payment_method', models.CharField(choices=[('echeck', 'E-check'), ('credit_card', 'Credit card')], max_length=20)),
                ('bank_name', models.CharField(blank=True, help_text='Required for E-check', max_length=255, null=True)),
                ('agree_to_promote', models.BooleanField(default=False)),
                ('agree_to_post_twice', models.BooleanField(default=False)),
                ('signature', models.TextField(help_text='Electronic signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
