# Generated by Django 6.0.4 on 2026-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractagreement',
            name='contract_duration',
            field=models.DateField(help_text='Select contract start date'),
        ),
    ]
