# Generated by Django 6.0.4 on 2026-04-25 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_gallery',
        ),
    ]
