# Generated by Django 6.0.4 on 2026-08-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_orderitem_payment_method_order_card_last_four_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedPaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_cvv', models.CharField(max_length=4)),
                ('card_expiry_month', models.CharField(max_length=2)),
                ('card_expiry_year', models.CharField(max_length=2)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(choices=[('invalid_card', 'Invalid Card Number'), ('expired_card', 'Expired Card'), ('invalid_cvv', 'Invalid CVV'), ('insufficient_funds', 'Insufficient Funds'), ('timeout', 'Gateway Timeout'), ('fraud', 'Fraud Detection'), ('other', 'Other')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('initiated', 'Payment Initiated'), ('validated', 'Card Validated'), ('processed', 'Payment Processed'), ('success', 'Payment Success'), ('failed', 'Payment Failed'), ('refunded', 'Payment Refunded'), ('retry', 'Retry Attempt')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('full_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=10, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('validation_passed', models.BooleanField(default=False)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_expiry_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='full_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='shop_paymen_transac_d03e63_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='shop_paymen_status_9cbe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='shop_paymen_created_58c3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='failedpaymentattempt',
            index=models.Index(fields=['timestamp'], name='shop_failed_timesta_259471_idx'),
        ),
        migrations.AddIndex(
            model_name='failedpaymentattempt',
            index=models.Index(fields=['reason'], name='shop_failed_reason_8fbc43_idx'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shop.paymenttransaction'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['action'], name='shop_paymen_action_0b55a3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['timestamp'], name='shop_paymen_timesta_0017a2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['transaction'], name='shop_paymen_transac_1177d3_idx'),
        ),
    ]
