# Generated by Django 6.0.4 on 2026-08-18 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_failedpaymentattempt_paymentlog_order_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedpaymentattempt',
            name='is_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='failedpaymentattempt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failed_attempts', to='shop.order'),
        ),
        migrations.AddField(
            model_name='failedpaymentattempt',
            name='original_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.failedpaymentattempt'),
        ),
        migrations.AddIndex(
            model_name='failedpaymentattempt',
            index=models.Index(fields=['card_number'], name='shop_failed_card_nu_3a78a5_idx'),
        ),
    ]
