# Generated by Django 6.0.4 on 2026-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_failedpaymentattempt_is_retry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
